# Generated by Django 2.2.6 on 2019-10-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descrption',
            new_name='description',
        ),
    ]
